// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmiofahhwhanbslgiqss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtaW9mYWhod2hhbmJzbGdpcXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyOTAzNjAsImV4cCI6MjA2Mzg2NjM2MH0.lJfv-TyxIZxcScH72SAsA60vBjXRZCo7MDqezQ6_SHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);